# Page settings
baseurl = "http://maeljego.com"
languageCode = "en-us"
title = "CV de Maël Jégo"
theme = "hugo-orbit-theme"
DefaultContentLanguage = "fr"
# googleAnalytics = "UA-XXXXXXX-Y"
# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]
# Meta
description = "Curriculum Vitae de maël Jégo"
author = "Maël Jégo"
# Theme styles
# The original template comes with 6 colour schemes. You may choose styles below.
# "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
# are available. Also the source LESS files are included so
# it’s quick and easy to change the styling and colour scheme.
styles = "styles.css"

# Sidebar sections
# Profile section
[params.profile]
name = "Maël Jégo"
tagline = "Administrateur système et réseau"
avatar = "profile.png"

# Contact section
[params.contact]
enable = true

[[params.contact.list]]
class = "email"
icon = "fa-envelope"
url = "mailto:contact@maeljego.com"
title = "contact@maeljego.com"

#        [[params.contact.list]]
#        class = "phone"
#        icon = "fa-phone"
#        url = "tel:+1234567890"
#        title = "+1234567890"
#
#        [[params.contact.list]]
#        class = "website"
#        icon = "fa-globe"
#        url = "//portfoliosite.com"
#        title = "portfoliosite.com"
#
#        [[params.contact.list]]
#        class = "linkedin"
#        icon = "fa-linkedin"
#        url = "//linkedin.com/in/johndoe"
#        title = "linkedin.com/in/johndoe"
#
#        [[params.contact.list]]
#        class = "github"
#        icon = "fa-github"
#        url = "//github.com/username"
#        title = "github.com/username"
#
#        [[params.contact.list]]
#        class = "twitter"
#        icon = "fa-twitter"
#        url = "//twitter.com/username"
#        title = "@twittername"
#
# Education section
[params.education]
enable = true
title = "Éducation"

[[params.education.list]]
degree = "Formation Niv. 5 BTS – Administrateur systèmes réseaux Gnu/Linux Windows"
college = "École CGSAT, Guyancourt"
dates = "2010"

[[params.education.list]]
degree = "Baccalauréat professionnel Commerce"
college = "CFA AFIP, Coignière, mention bien, en alternance dans la société CJD Poiret (commerce en électroménager)."
dates = "2000 - 2001"

# Languages section
[params.language]
enable = true
title = "Langues"

[[params.language.list]]
language = "Français"
level = "Natif"

[[params.language.list]]
language = "Anglais"
level = "Professionel"

#        [[params.language.list]]
#        language = "Russian"
#        level = "Professional"
# Interests section
[params.interests]
enable = true
title = "Intérêts"

[[params.interests.list]]
interest = "Open Source"

[[params.interests.list]]
interest = "Personnal Hosting"

[[params.interests.list]]
interest = "Neutralité du Net"

# Main body sections
# You may use markdown in summary, details and intro fields. But don't overdose, (it's resume!:)
# Summary section
[params.summary]
enable = true
icon = "fa-user"
title = "Career Profile"
summary = "**Administrateur système et réseau expérimenté avec plus de 10 ans d’expérience dans le support informatique**. Je porte un intérêt particulier pour le réseau (switch et firewall) et les systèmes GNU/Linux. Mon passage sur différents postes m'ont apporté une expérience dans la gestion des incidents et une connaissance du rôle des différents acteurs d'une chaîne de support."

# Experiences section
[params.experiences]
enable = true
icon = "fa-briefcase"
title = "Experiences"

[[params.jobs.list]]
position = "Incident/Problem Manager"
dates = "Janvier 2024 à ce jour"
company = "Neurones IT, La Défense"
details = "**Client: Groupe agroindustriel français (7500 utilisateurs)**, La Défense. Pour les équipes d'infrastructure (On-site, cloud privé en datacenter et cloud publique). Evaluation des incidents et coordinations des équipes techniques jusqu'a résolution. Communication et coordination lors des incidents majeurs. Amélioration des processus de prise en charge des incidents et demandes de changement. Coordination des équipes techniques dans la résolution des problèmes."

[[params.jobs.list]]
position = "Administrateur système et réseau (Référent technique)"
dates = "Janvier 2023 à Décembre 2023"
company = "Neurones IT, La Défense"
details = "**Client: Porté chez Cloud-Temple pour le même groupe agroindustriel français (7500 utilisateurs)**, La Défense. Référent technique pour le centre de service. Exploitation en remote des serveurs on-site et en Datacenter Windows et Linux (usines et bureaux du groupe), administration des flux firewalls Fortinet, administrations des comptes VPN Fortinet, trouble-shooting réseau Lan et Wan. Environnement: Firewall Fortinet, VM Ware 5.6 à 5.0, serveurs Windows 2003 à 2019, Active Directory, DNS, DHCP, RDS 2008, Infra Wifi Cisco, MPLS Orange WAN. Linux Red Hat, Oracle Linux, CentOS, Debian."

[[params.jobs.list]]
position = "Administrateur système et réseau (Niveau 1 et 2)"
dates = "Février 2019 - Décembre 2022"
company = "Neurones IT, La Défense"
details = "**Client: Groupe agroindustriel français (7500 utilisateurs)**, La Défense. Exploitation des serveurs on-site Windows et Linux (usines et bureaux), administration des flux firewalls, administrations des comptes VPN Fortinet, administration des comptes de téléphonie Orange B2GASS, Cisco CUCM, Avaya, trouble-shooting réseau Lan et Wan. Environnement: Firewall Fortinet, Checkpoint, VM Ware 5.5 à 5.0, serveurs Windows 2003 à 2019, Active Directory, DNS, DHCP, RDS 2008, Infra Wifi Cisco, VoIP Orange B2GASS, MPLS Orange WAN. Linux Red Hat, Oracle Linux, CentOS, Debian."

[[params.jobs.list]]
position = "Technicien support de proximité"
dates = "Février 2018 - Janvier 2019"
company = "Helpline, Nanterre"
details = "**Client: Groupe agroindustriel français (7500 utilisateurs)**, La Défense. Support VIP pour le DSI et ses équipes proches, le projet de migration SAP, les équipes d’administration système, l’équipe de déploiement poste de travail (Windows 10) ainsi que l’équipe de dev ABAP et Intranet Drupal. Environnement: SAP 7.50, SCCM, Windows 10, Office 365, Service Now, Jira, One2Team, Cisco Umbrella, Forticlient."

[[params.jobs.list]]
position = "Technicien migration poste de travail"
dates = "Octobre 2017 - Janvier 2018"
company = "Helpline, Nanterre"
details = "**Client: Groupe agroindustriel français (7500 utilisateurs)**, siège social, Paris 8ème arrondissement. Déploiement (Windows 10) Pour les collaborateurs VIP (Directions et traders)."

[[params.jobs.list]]
position = "Technicien support de proximité"
dates = "Novembre 2014 - Septembre 2017"
company = "Helpline, Nanterre"
details = "**Client: Groupe agroindustriel français (7500 utilisateurs)**, Tour Égée, La Défense. Pour les collaborateurs du projet de migration SAP. Support de proximité (Incidents poste de travail, nouveaux arrivants...). Administration Active Directory Niv 1 et 2 en environnement de prod et de test. Participation à la mise en place et au troubleshooting du client SAP GUI en prod,preprod,test. Packaging, patching, testing et paramétrage de SAP GUI 7.40 à 7.50 avant de laisser la main à l’équipe de déploiement SCCM. Mise en place et support des outils de développement (Eclipse, VS Note, ABAP, Python, Java, Drupal). Participation à la recette de l’outils de ticketing de la future infogérance (Service Now). Collecte et mise en page de la documentation client pour intégration dans service-now. Environnement: Altiris, Windows XP et SEVEN, Lotus Note, One2Team"

[[params.jobs.list]]
position = "Technicien Projet"
dates = "Octobre 2014"
company = "Helpline, Nanterre"
details = "**Client: Groupe Saint-Gobain**, siège social La Défense. Mise en place d'un environnement de test 'Druva inSync endpoint backup'. Déploiement On Premise de 3 serveurs (Master et Node), Simulation d'upgrade et montées de version, benchmarking, tolérance de panne (simulation de pannes système et réseau). Réalisation en Anglais des rapports de test, DEX (N1,N2,N3) et DAT. Montée de version du MASTER et des 2 NODES déja en production pour la direction du groupe."

[[params.jobs.list]]
position = "Technicien migration mobilité VIP"
dates = "Septembre 2014"
company = "Helpline, Nanterre"
details = " **Client: Louis Vuitton**, siège social Paris. Migration des terminaux mobiles de la direction du groupe (100 utilisateurs, langue anglais et français) de Blackberry vers Iphone et Ipad, transfert des données et paramétrage. enrôlement des terminaux dans le MDM Airwatch."

[[params.jobs.list]]
position = "Technicien support confirmé N2 Remote"
dates = "2011 - 2014"
company = "Helpline, Nanterre"
details = "**Client: Groupe Saint-Gobain**, Résolution des incidents complexes sur l’ensemble des utilisateurs distants (Home office, commerciaux, expatriés, VIP). Gestion des comptes VPN (RSA Secure Id et SafeNet/MobilePass – Client Cisco AnyConnect), Gestion des terminaux mobiles dans le MDM MobileIron. Référent technique aux équipes de déploiement de poste de travail dans le cadre de la migration vers Windows Seven. Référent technique pour les techniciens de proximité sur les différents sites France."

[[params.jobs.list]]
position = "Technicien Help-Desk N1"
dates = "2010 - 2011"
company = "Helpline, Nanterre"
details = "**Client: Groupe Saint-Gobain**, Gestion et prise en charge des incidents de l’environnement bureautique du client en anglais et français. Environnement : Microsoft SMS/SCCM, Windows XP et SEVEN, Microsoft Office 2003/2010, SAP 6.40, applicatifs métiers, Easy Vista."

[[params.jobs.list]]
position = "Responsable de point de vente"
dates = "2008 - 2009"
company = "Espace Loggia, Le Chesnay"
details = "Commerce en mobilier, corner-shop au sein du BHV de parly2. Vente de lits mezzanine, lits escamotables et meubles gain de place sur mesure. Gestion commerciale et administrative des commandes. Prise en charge des dossiers SAV. Utilisation professionnelle de la suite Open Office en environnement Gnu/Linux Ubuntu."

[[params.jobs.list]]
position = "Vendeur/conseiller en show-room"
dates = "2006 - 2008"
company = "Show-room-2001.com, Paris 1er"
details = "Vente au détail d'électroménager haut de gamme sur rendez-vous à un portefeuille de clients pro (architectes d’intérieur, cuisinistes...) et accueil de leurs clients en show-room, Hotline commerciale du site Internet (conseil uniquement), gestion commerciale des commandes."

[[params.jobs.list]]
position = "Vendeur/conseiller en magasin"
dates = "2001 - 2006"
company = "CJD Poiret (commerce en électroménager), Vélizy-Villacoublay"
details = "Vente au détail d’électroménager. administration du fond de caisse, reporting du C.A, contrôle des dossiers de financement, ouverture/fermeture du magasin, **support informatique en interne et interlocuteur de la sous-traitance informatique (SSII) pour la mise en place et la maintenance du parc informatique de la société (postes sous Windows XP, serveurs de fichier sous Windows Server 2003)**, **définition des besoins et achat du matériel informatique** pour les quatre magasins et le siège social, création d’un projet de site de vente en ligne (Mars 2006), **parrainage d’un apprenti en Bac Commerce**."

# Projects section
[params.projects]
enable = false
icon = "fa-archive"
title = "Projects"
intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

[[params.projects.list]]
title = "Hugrid"
url = "https://github.com/aerohub/hugrid"
tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

[[params.projects.list]]
title = "Simple FAQ Theme for Hugo"
url = "https://github.com/aerohub/hugo-faq-theme"
tagline = "Simple FAQ Theme for Hugo. You may use this theme for building very simple FAQs or note lists."

[[params.projects.list]]
title = "Hugo Identity"
url = "https://github.com/aerohub/hugo-identity-theme"
tagline = "Little profile/card-style template for Hugo."

[[params.projects.list]]
title = "Orbit"
url = "https://github.com/aerohub/hugo-orbit-theme"
tagline = "Hugo Resume/CV Theme for Developers."

[[params.projects.list]]
title = "Me"
url = "https://github.com/aerohub/hugo-me-theme"
tagline = "A simple responsive Hugo theme for personal site."

# Skills section
[params.skills]
enable = true
icon = "fa-rocket"
title = "Skills & Proficiency"

[[params.skills.list]]
skill = "GNU/Linux"
level = "70%"

[[params.skills.list]]
skill = "Windows"
level = "40%"

[[params.skills.list]]
skill = "Firewall"
level = "60%"

[[params.skills.list]]
skill = "Network Troubleshooting"
level = "70%"

[[params.skills.list]]
skill = "VPN"
level = "50%"

[[params.skills.list]]
skill = "Communication interpersonnelle"
level = "90%"

# Footer section
# The original template is released under the Creative Commons Attribution 3.0 License.
# Please keep the original attribution link when using for your own project.
# If you'd like to use the template without the attribution,
# you can check out other license options via template author's website: themes.3rdwavemedia.com
#
# As for Hugo port you may rewrite the "Ported for..." line with setting your name below.
[params.footer]
copyright = ""
